name: Anda RPM

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      runsOn:
        required: false
        default: ubuntu-latest
        type: string
      subatomicServer:
        required: false
        default: https://subatomic.fyralabs.com
        type: string
      subatomicRepo:
        required: false
        type: string
      upload:
        required: false
        default: false
        type: boolean
      mockConfig:
        required: true
        type: string
      mockConfigPackage:
        required: true
        type: string
    secrets:
      subatomicToken:
        required: false

jobs:
  build:
    runs-on: ${{ inputs.runsOn }}
    container:
      image: fedora:37
      options: --cap-add=SYS_ADMIN --privileged
    steps:

      - name: Install DNF plugins
        run: |
          dnf install -y dnf-plugins-core

      - name: Add repository
        run: |
          dnf config-manager --add-repo https://github.com/FyraLabs/subatomic-repos/raw/main/${{ inputs.subatomicRepo }}.repo
      - name: Install mock configs
        run: |
          dnf install -y createrepo_c git gcc curl wget anda subatomic-cli ${{ inputs.mockConfigPackage }}
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Build with Anda
        run: anda build ${{ inputs.name }} --package rpm -c ${{ inputs.mockConfig }}
      - name: Pack Build
        run: tar -cf anda-build.tar anda-build
      - name: Upload Build as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: anda-build-${{ inputs.runsOn }}.tar
          path: anda-build.tar
      - name: Upload to Subatomic
        run: subatomic-cli upload --server ${{ inputs.subatomicServer }} --token ${{ secrets.subatomicToken }} ${{ inputs.subatomicRepo }} anda-build/rpm/rpms/* anda-build/rpm/srpm/*
        if: ${{ inputs.upload }}
