name: Anda RPM

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      runsOn:
        required: false
        default: ubuntu-latest
        type: string
      subatomicServer:
        required: false
        default: https://subatomic.fyralabs.com
        type: string
      subatomicRepo:
        required: false
        type: string
      upload:
        required: false
        default: false
        type: boolean
      mockConfig:
        required: true
        type: string
      mockConfigPackage:
        required: true
        type: string
    secrets:
      subatomicToken:
        required: false

jobs:
  build:
    runs-on: ${{ inputs.runsOn }}
    container:
      image: registry.fedoraproject.org/fedora:37
      options: --cap-add=SYS_ADMIN --privileged
    steps:

      - name: Install DNF plugins
        run: |
          dnf install -y dnf-plugins-core

      - name: Add repository
        run: |
          dnf config-manager --add-repo https://github.com/andaman-common-pkgs/subatomic-repos/raw/main/${{ inputs.subatomicRepo }}.repo
      - name: Install packages
        run: |
          dnf install -y createrepo_c git gcc curl wget anda subatomic-cli ${{ inputs.mockConfigPackage }}
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 1
      - name: Set up git repository
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Build with Anda
        run: anda build ${{ inputs.name }} --package rpm -c ${{ inputs.mockConfig }} 2>&1
      - name: Upload Build as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: anda-build-rpm
          path: anda-build/rpm/**/*.rpm
      - name: Upload to Subatomic
        run: subatomic-cli upload --server ${{ inputs.subatomicServer }} --token ${{ secrets.subatomicToken }} ${{ inputs.subatomicRepo }} anda-build/rpm/rpms/*
        if: ${{ inputs.upload }}
