name: Build RPM

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - run: sudo dnf install -y rpmdevtools make git ${{ inputs.extraBuildPackages }}
      - uses: actions/checkout@v3
      - run: rpmdev-setuptree
      - run: git config --global user.name "Runner"
      - run: git config --global user.email "runner@example.com"
      - run: make archive
      - run: mv ${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}.tar.gz ~/rpmbuild/SOURCES
      - run: rpmbuild -ba ${{ env.PACKAGE_NAME }}.spec --define "_rpmdir $(pwd)" --define "_srcrpmdir $(pwd)"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}.${{ env.PACKAGE_ARCH }}.rpm
          path: "**/*.rpm"
