name: Build and Push Flatpak

on:
  workflow_call:
    inputs:
      manifest:
        required: true
        type: string
      secrets:
        repoToken:
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:36
    steps:
      - run: sudo dnf install -y flatpak flatpak-builder
      - uses: actions/checkout@v3
      - run: flatpak-builder --install-deps-from=flathub --repo=local-repo build ${{ inputs.manifest }}
      - name: Upload Flatpak
        run: |
          export FLATPAK_BUILD=$(flat-manager-client create https://catalogue.tauos.co/manager/ stable)
          flat-manager-client push --commit $FLATPAK_BUILD local-repo
          flat-manager-client publish $FLATPAK_BUILD
        env:
          REPO_TOKEN: ${{ secrets.repoToken }}