name: Build RPM

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      archs:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:36
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - run: sudo dnf install -y rpmdevtools make git mock
      - uses: actions/checkout@v3
      - run: rpmdev-setuptree
      - run: git config --global user.name "Runner"
      - run: git config --global user.email "runner@example.com"
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - run: echo "VERSION=$(awk '/Version:/ { print $2 }' ${{ inputs.name }}.spec)" >> $GITHUB_ENV
      - run: echo "RELEASE=$(awk '/Release:/ { print $2 }' ${{ inputs.name }}.spec | sed 's|%{?dist}||g')" >> $GITHUB_ENV
      - run: echo "TAG=${{ inputs.name }}-$VERSION" >> $GITHUB_ENV
      - run: git archive --format=tar --prefix=${{ inputs.name }}-$VERSION/ HEAD > $TAG.tar
      - run: gzip -f $TAG.tar
      - run: spectool -g -R ${{ inputs.name }}.spec
      - run: rpmbuild -bs ${{ inputs.name }}.spec --define "_rpmdir $(pwd)" --define "_srcrpmdir $(pwd)" --undefine=_disable_source_fetch --define '_sourcedir .'
      - run: |
          for arch in ${{ inputs.archs }}
          do
            mock --isolation=chroot --resultdir . --arch=$arch *.src.rpm
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}-unsigned
          path: "**/*.rpm"
