name: Build OSTree

on:
  workflow_call:
    inputs:
      ostreeRef:
        required: true
        type: string
      osVariant:
        required: true
        type: string
      osName:
        required: true
        type: string
      unifiedCore:
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # Yes, this is unstable, but it also might fix things. Remove when new rpm-ostree patche is merged into stable
      image: fedora:rawhide
      options: --privileged
    steps:
      - run: sudo dnf install ostree rpm-ostree selinux-policy -y
      - uses: actions/checkout@v3
      - run: ostree init --repo build-tree --mode archive
      - name: Cache
        uses: actions/cache@v3
        with:
          path: build-tree-cache
          key: ${{ inputs.ostreeRef }}
      - run: mkdir -p build-tree-cache
      - run: sudo rpm-ostree compose tree core.yaml --repo ../build-tree --cachedir=../build-tree-cache $FLAGS
        env:
          FLAGS: ${{ inputs.unifiedCore == 'true' && '--unified-core' || '' }}
        working-directory: ${{ inputs.osVariant }}
      - run: sudo chmod -R 777 ../build-tree
        working-directory: ${{ inputs.osVariant }}
      - run: ostree summary --repo ../build-tree -u
        working-directory: ${{ inputs.osVariant }}
      - run: tar -cf build-tree.tar build-tree
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.osName }}
          path: build-tree.tar
