name: Compose OSTree

on:
  workflow_call:
    inputs:
      ostreeRef:
        required: true
        type: string
      osVariant:
        required: true
        type: string
      upload:
        required: false
        default: false
        type: boolean
    secrets:
      signingKey:
        required: true
      privateKey:
        required: true
jobs:
  build:
    uses: .github/workflows/build-ostree.yml@main
    with:
      ostreeRef: ${{ inputs.ostreeRef }}
      osVariant: ${{ inputs.osVariant }}
  sign:
    needs: build
    uses: .github/workflows/sign-ostree.yml@main
    if: ${{ inputs.upload }}
    with:
      ostreeRef: ${{ inputs.ostreeRef }}
      signingKey: ${{ secrets.signingKey }}
    secrets:
      signingKey: ${{ secrets.signingKey }}
  upload:
    needs: sign
    uses: .github/workflows/upload-ostree.yml@main
    with:
      ostreeRef: ${{ inputs.ostreeRef }}
      upload: ${{ inputs.upload }}
    secrets:
      privateKey: ${{ secrets.privateKey }}
