name: Sign RPM

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      name:
        required: true
        type: string
      arch:
        required: true
        type: string
    secrets:
      signingKey:
        required: true

jobs:
  sign:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - uses: actions/download-artifact@v3
        name: ${{ inputs.name }}-${{ inputs.version }}.${{ inputs.arch }}.rpm
      - run: sudo dnf install -y rpm-sign
      - run: sudo rpm --import https://tauos.co/gpg.asc
      - run: echo "GPG_TTY=$(tty)" >> $GITHUB_ENV
      - name: Import Signing Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.signingKey }}
      - run: echo "%_signature gpg" >> ~/.rpmmacros
      - run: echo "%_gpg_path /github/home/.gnupg" >> ~/.rpmmacros
      - run: echo "%_gpg_name tauOS" >> ~/.rpmmacros
      - run: echo "%_gpgbin /usr/bin/gpg2" >> ~/.rpmmacros
      - run: echo "%__gpg_sign_cmd %{__gpg} gpg --force-v3-sigs --batch --verbose --no-armor --no-secmem-warning -u "%{_gpg_name}" -sbo %{__signature_filename} --digest-algo sha256 %{__plaintext_filename}'" >> ~/.rpmmacros
      - run: rpm --addsign **/*.rpm
      - run: rpm --checksig -v **/*.rpm
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}-${{ inputs.version }}.${{ inputs.arch }}.rpm
          path: "**/*.rpm"
