name: Sign RPM

on:
  workflow_call:

jobs:
  sign:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - uses: actions/download-artifact@v3
        name: ${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}.${{ env.PACKAGE_ARCH }}.rpm
      - run: sudo dnf install -y rpm-sign
      - run: sudo rpm --import https://tauos.co/gpg.asc
      - name: Import Signing Key
        run: |
          echo -n "$GPG_PRIVATE_KEY" | gpg --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      # TODO there has to be a better way to handle this, this is a really fucking dumb way of doing this
      - run: sudo -u root bash
      - run: echo "%_signature gpg" >> ~/.rpmmacros
      - run: echo "%_gpg_path /root/.gnupg" >> ~/.rpmmacros
      - run: echo "%_gpg_name tauOS" >> ~/.rpmmacros
      - run: echo "%_gpgbin /usr/bin/gpg2" >> ~/.rpmmacros
      - run: echo "%__gpg_sign_cmd %{__gpg} gpg --force-v3-sigs --batch --verbose --no-armor --no-secmem-warning -u "%{_gpg_name}" -sbo %{__signature_filename} --digest-algo sha256 %{__plaintext_filename}'" >> ~/.rpmmacros
      - run: rpm --addsign **/*.rpm
      - run: rpm --checksig -v **/*.rpm
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}.${{ env.PACKAGE_ARCH }}.rpm
          path: "**/*.rpm"
