name: Upload OSTree

on:
  workflow_call:
    inputs:
      osName:
        required: true
        type: string
    secrets:
      repoKnownHosts:
        required: true
      repoPrivateKey:
        required: true
      repoIP:
        required: true
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.osName }}
      - run: tar -xf *.tar
      - name: Install Dependencies
        run: sudo apt-get install -y libostree-dev
      - run: pip3 install ostree-push
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.repoPrivateKey }}
          known_hosts: ${{ secrets.repoKnownHosts }}
      - run: ostree-push --repo build-tree repo@${{ secrets.repoIP }}:/var/www/repo.tauos.co/ostree
