name: Upload OSTree

on:
  workflow_call:
    inputs:
      osName:
        required: true
        type: string
    secrets:
      privateKey:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.osName }}
      - run: tar -xf *.tar
      - name: Install Dependencies
        run: apt-get install -y libostree-dev python3
