name: Upload OSTree

on:
  workflow_call:
    inputs:
      osName:
        required: true
        type: string
    secrets:
      privateKey:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.osName }}
      - run: tar -xf *.tar
      - name: Install Dependencies
        run: sudo apt-get install -y libostree-dev
      - run: pip3 install ostree-push
      - run: sudo curl https://deb.releases.teleport.dev/teleport-pubkey.asc -o /usr/share/keyrings/teleport-archive-keyring.asc
      - run: echo "deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] https://deb.releases.teleport.dev/ stable main" | sudo tee /etc/apt/sources.list.d/teleport.list > /dev/null
      - run: sudo apt-get update -y
      - run: sudo apt-get install teleport -y
      - run: echo "$TELEPORT_IDENTITY" > identity
        env:
         TELEPORT_IDENTITY: ${{ secrets.TELEPORT_IDENTITY }}
      - run: tsh -i identity config > ~/.ssh/config
      - run: ostree-push --repo build-tree repo@tau-repo.access.fyralabs.com:/var/www/repo.tauos.co/ostree
