name: Upload RPM

on:
  workflow_call:
    inputs:
      tauOSVersion:
        required: true
        type: string
      version:
        required: true
        type: string
      name:
        required: true
        type: string
      arch:
        required: true
        type: string
    secrets:
      privateKey:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.name }}-${{ inputs.version }}.${{ inputs.arch }}
      - run: sudo curl https://deb.releases.teleport.dev/teleport-pubkey.asc -o /usr/share/keyrings/teleport-archive-keyring.asc
      - run: echo "deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] https://deb.releases.teleport.dev/ stable main" | sudo tee /etc/apt/sources.list.d/teleport.list > /dev/null
      - run: sudo apt-get update -y
      - run: sudo apt-get install teleport -y
      - run: echo "$TELEPORT_IDENTITY" > identity
        env:
         TELEPORT_IDENTITY: ${{ secrets.TELEPORT_IDENTITY }}
      - run: tsh ssh -i identity yumrepo@repo.tauos.co "mkdir -p /var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/"
      - run: tsh scp -i identity **/*.rpm yumrepo@repo.tauos.co:/var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/
      - run: tsh ssh -i identity yumrepo@repo.tauos.co "createrepo --update /var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/"
      - run: tsh ssh -i identity yumrepo@repo.tauos.co "rm -f /var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/repodata/repomd.xml.asc && gpg --output /var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/repodata/repomd.xml.asc -u tauOS --no-tty --detach-sign --armor /var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/repodata/repomd.xml"
