name: Upload RPM

on:
  workflow_call:
    inputs:
      tauOSVersion:
        required: true
        type: string
    secrets:
      privateKey:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        name: ${{ inputs.name }}-${{ inputs.version }}.${{ inputs.arch }}
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.privateKey }}
          ssh-host: repo.tauos.co
      - run: ssh yumrepo@repo.tauos.co "mkdir -p /var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/"
      - run: scp **/*.rpm yumrepo@repo.tauos.co:/var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/
      - run: ssh yumrepo@repo.tauos.co "createrepo --update /var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/"
      - run: ssh yumrepo@repo.tauos.co "rm -f /var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/repodata/repomd.xml.asc && gpg --output /var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/repodata/repomd.xml.asc -u tauOS --no-tty --detach-sign --armor /var/www/repo.tauos.co/releases/${{ inputs.tauOSVersion }}/repodata/repomd.xml"
